"""Add actor to AuditLog

Revision ID: 4bb5272f8721
Revises: 0bd8a41c7596
Create Date: 2025-11-13 22:24:20.967467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb5272f8721'
down_revision: Union[str, Sequence[str], None] = '0bd8a41c7596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'actor')
    # ### end Alembic commands ###
